version: '3'
services:
  reverse-proxy:
    image: traefik
    restart: always
    command: "--api --docker --docker.domain=local"
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  default:
    external:
      name: bridge