#!/usr/bin/env bash

docker network create traefik

docker network create registry

docker network create teamcity

docker network create monitoring

docker network create elasticsearch

docker network create selenoid

docker-compose up -d reverse-proxy
